version: 5
permit_join: false
homeassistant:
  enabled: true
advanced:
  log_level: info
  last_seen: ISO_8601
  channel: 26
  network_key:
    - 247
    - 55
    - 69
    - 12
    - 224
    - 146
    - 128
    - 5
    - 209
    - 19
    - 108
    - 94
    - 191
    - 255
    - 28
    - 239
  pan_id: 48348
  ext_pan_id:
    - 51
    - 6
    - 200
    - 127
    - 61
    - 57
    - 40
    - 222
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt_user
  password: dupa.123.mqtt
  base_topic: tasmota_g8
frontend:
  enabled: true
  port: 8099
availability:
  enabled: true
serial:
  port: tcp://192.168.2.168:8888
  adapter: ezsp
devices:
  '0x54ef44100129504f':
    friendly_name: S9 Rodzice Gora Smoke
  '0x00158d008b35fd5a':
    friendly_name: M1 Rodzice Dol
  '0x00158d008b77dd52':
    friendly_name: T10 Rodzice Dol
