version: 4
permit_join: false
homeassistant:
  enabled: true
advanced:
  log_level: info
  last_seen: ISO_8601
  channel: 25
  network_key:
    - 97
    - 133
    - 166
    - 228
    - 7
    - 36
    - 163
    - 230
    - 65
    - 145
    - 38
    - 23
    - 143
    - 200
    - 192
    - 187
  pan_id: 26386
  ext_pan_id:
    - 28
    - 204
    - 156
    - 254
    - 0
    - 177
    - 201
    - 235
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt_user
  password: dupa.123.mqtt
  base_topic: tasmota_g4
frontend:
  enabled: true
  port: 8099
serial:
  port: tcp://192.168.2.164:8888
  adapter: ezsp
availability:
  enabled: true
devices:
  '0xa4c1383679f6402d':
    friendly_name: T20 W3
  '0xa4c138e732a18894':
    friendly_name: P2 Kotlownia
  '0xa4c13832b48e187a':
    friendly_name: F2 Kotlownia
  '0x00158d008b77dd44':
    friendly_name: T7 Kot≈Çownia
  '0x54ef4410012949d0':
    friendly_name: '0x54ef4410012949d0'
  '0x00158d008b35dd1d':
    friendly_name: '0x00158d008b35dd1d'
blocklist: []
