version: 5
permit_join: false
homeassistant:
  enabled: true
advanced:
  network_key:
    - 64
    - 77
    - 204
    - 163
    - 54
    - 75
    - 132
    - 204
    - 122
    - 153
    - 253
    - 182
    - 36
    - 165
    - 239
    - 1
  channel: 11
  pan_id: 29739
  ext_pan_id:
    - 101
    - 140
    - 156
    - 91
    - 255
    - 226
    - 150
    - 120
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt_user
  password: dupa.123.mqtt
  base_topic: tasmota_g5
frontend:
  enabled: true
  port: 8099
availability:
  enabled: true
serial:
  port: tcp://192.168.2.165:8888
  adapter: ezsp
devices:
  '0x54ef441001243f60':
    friendly_name: S7 W4 6AX
  '0x00158d008b7ca770':
    friendly_name: T2 W4
  '0x00158d008b85c810':
    friendly_name: C2 W4 brama
  '0xa4c138bed62ce9bb':
    friendly_name: '0xa4c138bed62ce9bb'
blocklist: []
